### ISSUE TITLE
[Bug]: A panel has been registered without an `id()`

### ISSUE THREAD

**Issue by galliroberto** [savannabits/filament-modules#107]
### What happened?

I have created a new module and a new cluster.
When I visit a page I get: _A panel has been registered without an id()_

![image](https://github.com/savannabits/filament-modules/assets/4560537/b3673039-9933-40e7-b8a4-aabb3a0390fd)

![image](https://github.com/savannabits/filament-modules/assets/4560537/d0a43b6e-6092-4e73-a022-ab9ad0747bd8)

### How to reproduce the bug

php artisan module:make LaboratoryRepair
php artisan module:filament:install LaboratoryRepair

visit a web page

### Package Version

4.0.6

### PHP Version

8.2

### Laravel Version

11

**Comment by galliroberto** [comment]
Solved move plugin under id

![image](https://github.com/savannabits/filament-modules/assets/4560537/6e6bd4d3-c9e7-4c69-9cbb-0f7ae3c17228)

**Comment by coolsam726** [comment]
@galliroberto thanks for reporting this. The package attempts to modify the AdminPanelProvider if you choose that option during installation, but I recommend that you still have a look at that file and organize it manually as you have done since this is usually not an accurate operation. I hope everything else works.
